### ISSUE TITLE
Python 2 will be deprecated 1/1/2020. Consider teaching a modern version

### ISSUE THREAD

**Issue by ZacharyJoswick** [freemanbach/Python#1]
Python 2 will be deprecated at the beginning of next year. I understand that you are teaching for a university and as such will be teaching useless, out of date tools and frameworks, but python 3 has been out for over 10 years at this point.

For reference: [Deprication Clock](https://pythonclock.org/)

**Comment by freemanbach** [comment]
it is True that Python won't be supported by January 2020. However, python 2.7.x language and grammar in itself hasn't changed significantly enough where it rendered python2 useless.  Much of the IT industry is currently on Python2, perhaps in the process of migrating to Python3.  Python2 remained to be resourceful powerful, useful , and functional in many industries especially in Data Science.  As i can see the paradigm shift of python3 wanting to become more like java and in the way of Object Oriented programming along with many aspects of language improvements, python2 has had these changes implemented to the latest version 2.7.x.     Students can still be benefited from many of the consistencies of variables, expressions, statements, conditional statements, lists, dictionary, lambda, error handling, fileIO, even OO by learning python2, which remained to be the same in python3.  Also, it is certainly beneficial to educate students on python3, when January 2020 comes around. Thanks for bringing this up.
